import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1a1a1a', 
    padding: 20,
  },
  label: {
    fontSize: 18,
    color: '#ffcc00',
    marginBottom: 10,
  },
  input: {
    width: '100%',
    height: 50,
    backgroundColor: '#fff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ccc',
    paddingHorizontal: 15,
    fontSize: 16,
    color: '#333', 
    marginBottom: 15,
  },
  button: {
    backgroundColor: '#ffcc00', 
    paddingVertical: 15,
    paddingHorizontal: 40,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5, 
  },
  image: {
    width: 250,
    height: 170,
    borderWidth: 6,
    borderColor: '#FFFFFF', 
    alignSelf: 'center',
    marginBottom: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 6, 
  },
  buttonText: {
    fontSize: 18,
    color: '#1a1a1a', 
    fontWeight: 'bold',
    textAlign: 'center',
  },
  result: {
    fontSize: 24,
    marginTop: 30,
    fontWeight: 'bold',
    color: '#00ff00',
  },
});